version: '3'

services:
    nginx:
        image: ${REGISTRY_ADDRESS}/nginx:${IMAGE_TAG}
        restart: always
        depends_on:
            - php-fpm
        ports:
            - "80:80"

    php-fpm:
        image: ${REGISTRY_ADDRESS}/php-fpm:${IMAGE_TAG}
        restart: always
        environment:
            APP_SECRET: ${MANAGER_APP_SECRET}
            DATABASE_URL: pgsql://app:${MANAGER_DB_PASSWORD}@postgres:5432/app
            REDIS_URL: tcp://redis:6379?password=${MANAGER_REDIS_PASSWORD}
            MAILER_URL: null://localhost
            OAUTH_FACEBOOK_SECRET: ${MANAGER_OAUTH_FACEBOOK_SECRET}
        depends_on:
            - postgres
            - redis

    php-cli:
        image: ${REGISTRY_ADDRESS}/php-cli:${IMAGE_TAG}
        environment:
            APP_SECRET: ${MANAGER_APP_SECRET}
            DATABASE_URL: pgsql://app:${MANAGER_DB_PASSWORD}@postgres:5432/app
            REDIS_URL: tcp://redis:6379?password=${MANAGER_REDIS_PASSWORD}
            MAILER_URL: null://localhost
            OAUTH_FACEBOOK_SECRET: ${MANAGER_OAUTH_FACEBOOK_SECRET}
        depends_on:
            - postgres
            - redis

    postgres:
        image: ${REGISTRY_ADDRESS}/postgres:${IMAGE_TAG}
        restart: always
        volumes:
            - postgres:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: ${MANAGER_DB_PASSWORD}
            POSTGRES_DB: app

    redis:
        image: redis:3.0-alpine
        restart: always
        volumes:
            - redis:/data
        command: redis-server --requirepass ${MANAGER_REDIS_PASSWORD}

volumes:
    postgres:
        driver: local
    redis:
        driver: local
