version: '3'

services:
  nginx:
    build:
      context: docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm
    networks:
      - internal

  php-fpm:
    build:
      context: docker/dev/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.220.1 remote_enable=1"
      PHP_IDE_CONFIG: "serverName=Docker"
    networks:
      - internal

  php-cli:
    build:
      context: docker/dev/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    tty: true
    networks:
      - internal

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - 54321:5432
    networks:
      - internal

volumes:
  postgres:
    driver: local
  composer:
    driver: local

networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.220.0/28
