version: '3'

services:
  nginx:
    build:
      context: docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/dev/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  php-cli:
    build:
      context: docker/dev/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - composer:/root/.composer/cache
    tty: true

  postgres:
    image: postgres:11.2-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: app
    ports:
      - 54321:5432

volumes:
  postgres:
    driver: local
  composer:
    driver: local
