version: '3'

services:
  nginx:
    build:
      context: docker/dev/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - 8080:80
    depends_on:
      - php-fpm

  php-fpm:
    build:
      context: docker/dev/php-fpm
      dockerfile: Dockerfile
    volumes:
      - ./:/app

  php-cli:
    build:
      context: docker/dev/php-cli
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    tty: true
